<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131217125541 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("CREATE TABLE lelesys_plugin_forum_domain_model_postvisit (persistence_object_identifier VARCHAR(40) NOT NULL, ipaddress VARCHAR(255) NOT NULL, sessionidentifier VARCHAR(255) NOT NULL, postnodeidentifier VARCHAR(255) NOT NULL, createddate DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE lelesys_plugin_forum_domain_model_watcher (persistence_object_identifier VARCHAR(40) NOT NULL, user VARCHAR(40) DEFAULT NULL, objecttype VARCHAR(255) NOT NULL, objectidentifier VARCHAR(255) NOT NULL, INDEX IDX_FA984BA78D93D649 (user), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE lelesys_plugin_forum_domain_model_watcher ADD CONSTRAINT FK_FA984BA78D93D649 FOREIGN KEY (user) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("DROP TABLE lelesys_plugin_forum_domain_model_postvisit");
		$this->addSql("DROP TABLE lelesys_plugin_forum_domain_model_watcher");
	}
}
